config/routes.rb
Rails.application.routes.draw do

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy, :edit, :update]

  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new

  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to new_cocktail_dose_path(@cocktail), notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, :photo_cache)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:destroy, :update, :edit]
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # we need `cocktail_id` to asssociate dose with corresponding restaurant
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def edit
  end

  def update
    cocktail = @dose.cocktail
    @dose.update_attributes(dose_params)
    redirect_to cocktail_path(cocktail)
  end

  def destroy
    cocktail = @dose.cocktail
    @dose.destroy
    respond_to do |format|
      format.html { redirect_to cocktail_path(cocktail), notice: 'Dose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cocktails</h1>

<% @cocktails.each do |cocktail| %>

  <div class="card"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path @cocktail.photo, height: 300, width: 400, crop: :fill %>')">
    <div class="card-category"><%= cocktail.name %></div>
    <div class="card-description">
      <p>Cocktail</p>
    </div>
    <a class="card-link" href="#" ></a>
  </div>

  <%= link_to 'Show', cocktail %> |
  <%= link_to 'Edit', edit_cocktail_path(cocktail) %> |
  <%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

<%= link_to 'Add a new Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1>Your cocktail</h1>

<h2><%= @cocktail.name %></h2>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

<h3>Ingredients:</h3>

<% @cocktail.doses.each do |dose| %>
  <p>
    <%= dose.description %>
    <%= dose.ingredient.name %>
    <%= link_to 'Destroy', dose_path(dose), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Edit', edit_dose_path(dose) %>
  </p>
<% end %>

<hr>

<%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
<%= link_to 'Edit Cocktail name', edit_cocktail_path(@cocktail), class: "btn btn-primary" %>
<%= link_to 'Back to Cocktail list', cocktails_path, class: "btn btn-primary" %>
<hr>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
<h1>Add ingredients:</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
<!-- /cocktails/:cocktail_id/doses -->
  <%= f.error_notification %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.input :description %>
  <%= f.submit  "Edit an ingredient", class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h1>Add ingredients:</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
<!-- /cocktails/:cocktail_id/doses -->
  <%= f.error_notification %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.input :description %>
  <%= f.submit  "Add an ingredient", class: "btn btn-primary" %>
<% end %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'components/navbar' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'components/footer' %>

  </body>
</html>